<?php
/**
 * @file
 * Code for the Business Portal Wizard feature.
 */

include_once 'sbp_wizard.features.inc';

/**
* Implements hook_entity_info_alter().
*/
function sbp_wizard_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['json'] = array(
    'label' => t('json'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_block_info().
 */
function sbp_wizard_block_info() {
  $blocks = array();
  $blocks['wizard'] = array(
    'info' => t('Wizard Block'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function sbp_wizard_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'wizard':
      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => sbp_wizard_block(),

      );
      break;
  };
  return $block;
}

/**
 * Custom block for wizard HTML, and loading JS assets.
 */
function sbp_wizard_block() {

  drupal_add_js('profiles/labp/libraries/underscore/underscore-min.js');
  drupal_add_js('profiles/labp/libraries/backbone/backbone-min.js');
  drupal_add_js('profiles/labp/modules/bp/features/sbp_wizard/js/wizard/models.js');
  drupal_add_js('profiles/labp/modules/bp/features/sbp_wizard/js/wizard/collections.js');
  drupal_add_js('profiles/labp/modules/bp/features/sbp_wizard/js/wizard/views.js');
  drupal_add_js('profiles/labp/modules/bp/features/sbp_wizard/js/wizard/app.js');


  return

  '
  <div id="wizard" class="wizard">
      <div class="wizard__header"></div>
      <div class="wizard__intro-block"></div>
      <div class="wizard__tip">
        <div class="wizard__tip_icon"></div>
        <div class="wizard__tip_content">
          <p class="wizard__tip_copy"></p>
        </div>
      </div>
  </div> <!-- Close #wizard -->

  <script type="text/template" id="header-template">
    <div class="wizard__header--title--government"> {{Name}}</div>
    <div class="wizard__header--title"> {{title}}</div>
    <div class="wizard__header-line"></div>
  </script>

  <script type="text/template" id="intro">
    <div class="wizard__copy--section_intro">{{Description}}</div>
  </script>

  <script type="text/template" id="intro-with-illustration">
    <div class="wizard__illustration"><img src="{{illustration}}"></div>
    <div class="wizard__copy--section_intro">{{Description}}</div>
  </script>

  <script type="text/template" id="buttons">
    <div class="wizard__buttons"></div>
  </script>

  <script type="text/template" id="progress">
    <div class="wizard__col_2">
      <div class="wizard__progress-bar">
        <div class="wizard__progress-bar-indicator">
          <div class="wizard__progress-bar-icon"></div>
        </div>
        <ul class="wizard__progress-drawer"></ul>
      </div>
    </div>
  </script>

  <script type="text/template" id="progress">
    <div class="wizard__nav"></div>
  </script>
';
}
